name: 'AI Homework Judge Action'
description: 'Online Judging for the AI homework "No. 6" of PKU software practice course.'
author: pku-software
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: python "${{ github.action_path }}\src\main.py"  "${{ github.workspace }}"
      shell: PowerShell
